import react, { useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { WHITELIST_CONTRACT_ADDRESS, ABI } from '@/constants'
import { ethers } from 'ethers'
import { MetaMaskInpageProvider } from '@metamask/providers'


export default function Home() {

  const getSignerAndProvider = async (): Promise<(ethers.BrowserProvider | ethers.JsonRpcSigner)[] | undefined> => {
    try {
      const { ethereum } = window;
      const provider = new ethers.BrowserProvider(ethereum as MetaMaskInpageProvider)
      const signer = await provider.getSigner()
      console.log(signer, provider)
      const chainId = await (await provider.getNetwork()).chainId.toString()

      if (chainId !== "420n") {
        console.log("Connected to OP")
      } else {
        throw new Error("Please connect to the OP Network")
      }

      return [signer, provider]

    } catch (error) {
      console.log("Error with the getSigner method: ", error)
    }
  }


  const addAddressToWhitelist = async () => {
  };

  const getNumberOfWhitelisted = async () => {
  };

  const checkIfAddressInWhitelist = async () => {
  };

  const connectWallet = async () => {
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <button onClick={getSignerAndProvider}>Click Me</button>
        
      </main>
    </>
  )
}
