import react, { useState } from 'react'

import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { Web3Modal } from "@web3modal/standalone";
import SignClient from "@walletconnect/sign-client";
import { WHITELIST_CONTRACT_ADDRESS, ABI } from '@/constants'

if (!process.env.NEXT_PUBLIC_PROJECT_ID) {
  throw new Error("You need to provide NEXT_PUBLIC_PROJECT_ID env variable");
}

const web3Modal: Web3Modal = new Web3Modal({
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  walletConnectVersion: 2,
});

export default function Home() {

  const [walletConnected, setWalletConnected] = useState(false);
  const [joinedWhitelist, setJoinedWhitelist] = useState(false);
  const [loading, setLoading] = useState(false);
  const [numberOfWhitelisted, setNumberOfWhitelisted] = useState(0);

  const getProviderOrSigner = async (needSigner = false) => {
    
  };

  const addAddressToWhitelist = async () => {
  };

  const getNumberOfWhitelisted = async () => {
  };

  const checkIfAddressInWhitelist = async () => {
  };

  const connectWallet = async () => {
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.main}>
          <div>
            <h1 className={styles.title}>Welcome to Crypto Devs!</h1>
            <div className={styles.description}>
              {/* Using HTML Entities for the apostrophe */}
              It&#39;s an NFT collection for developers in Crypto.
            </div>
            <div className={styles.description}>
              {numberOfWhitelisted} have already joined the Whitelist
            </div>
          </div>
          <div>
            <img className={styles.image} src="./crypto-devs.svg" />
          </div>
        </div>

        <footer className={styles.footer}>
          Made with &#10084; by Crypto Devs
        </footer>
      </main>
    </>
  )
}
